server:
  port: 58080
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: springboot-demo
  profiles:
    # 开发环境：dev  测试环境：test  生产环境：prod
    # 生产环境如果要保证信息安全，可以将application-prod.yml里面的配置信息放到nacos配置里面
    active: test
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    ssl: true
    cluster:
      nodes: clustercfg.redis-cluster-prod-remt.y437u8.euw2.cache.amazonaws.com:6379 # Redis节点地址列表
      max-redirects: 5 # 最大重定向次数（默认为5）
